# Production specific values
redis:
  auth:
    enabled: true
    password: "redis-production-password" # Change this in production
  master:
    replicaCount: 1
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1Gi
  replica:
    replicaCount: 2
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1Gi
  service:
    type: ClusterIP
    ports:
      redis: 6379
